version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: "ls"
          command: "ls"
      - run:
          name: "pwd"
          command: "pwd"
      - run:
          name: "permission"
          command: "chmod 777 e2e_tests/startup.sh"
      - run:
          name: "Running tests"
          command: "./e2e_tests/startup.sh"
