version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: "ls"
          command: ls"
      - run:
          name: "permission"
          command: chmod 777 e2e_tests/startup.sh"
      - run:
          name: "Running tests"
          command: "docker run --rm --entrypoint=/bin/bash --name test -v $SOURCE_DIR/e2e_tests:/stms/qa sandeshb8/e2e_test:latest -c ls"